# Generated by Django 5.2 on 2025-05-14 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('medido_por', models.CharField(choices=[('UNIDADE', 'Unidade'), ('CENTO', 'Cento'), ('QUILO', 'Quilo')], default='UNIDADE', max_length=10)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=6)),
                ('oberservacoes', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
