# Generated by Django 5.2 on 2025-05-25 00:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_cliente', models.CharField(max_length=50)),
                ('numero_cliente', models.CharField(max_length=20)),
                ('endereco_cliente', models.TextField(max_length=100)),
                ('endereco_entrega', models.TextField(max_length=100)),
                ('valor', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('observacoes', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('medido_por', models.CharField(choices=[('UNIDADE', 'Unidade'), ('CENTO', 'Cento'), ('QUILO', 'Quilo')], default='UNIDADE', max_length=10)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=6)),
                ('observacoes', models.TextField(blank=True, max_length=75, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=6)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.pedido')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.produto')),
            ],
        ),
        migrations.AddField(
            model_name='pedido',
            name='produtos',
            field=models.ManyToManyField(through='website.ItemPedido', to='website.produto'),
        ),
    ]
