# Generated by Django 5.2 on 2025-05-26 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='observacoes',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
