# Generated by Django 5.2 on 2025-05-16 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='oberservacoes',
            new_name='observacoes',
        ),
    ]
