# Generated by Django 5.2 on 2025-05-17 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_rename_oberservacoes_produto_observacoes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='observacoes',
            field=models.TextField(blank=True, max_length=75, null=True),
        ),
    ]
