# Generated by Django 5.2 on 2025-05-11 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('observacoes', models.CharField(max_length=50)),
                ('preco_unidade', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Preço por unidade')),
                ('preco_cento', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Preço por Cento')),
                ('preco_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Preço por Kg')),
            ],
        ),
    ]
