# Generated by Django 5.2 on 2025-05-07 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('categoria', models.CharField(choices=[('BOLO', 'Bolo'), ('DOCE', 'Doce'), ('SALGADO', 'Salgado'), ('TORTA', 'Torta'), ('MASSA', 'Massa')], max_length=20)),
                ('preco_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Preço Unitário')),
                ('preco_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Preço por Kg')),
            ],
        ),
    ]
