# Generated by Django 5.2 on 2025-05-11 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='observacoes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
